#!/bin/sh
cat <(while cat "$1"; do :; done) | paplay --channel-map=front-left,rear-left &
cat <(while cat "$2"; do :; done) | paplay --channel-map=front-right,rear-right &

trap "exit" INT TERM
trap "kill 0" EXIT

sleep 10000000
